### ISSUE TITLE
TopNavigation title gets truncated when logo svg is scaled in percentage

### ISSUE THREAD

**Issue by YueyingLu** [cloudscape-design/components#704] opened 2023-02-03 11:08 UTC
### Discussed in https://github.com/cloudscape-design/components/discussions/606

<div type='discussions-op-text'>

<sup>Originally posted by **suvihaara** January  3, 2023</sup>
Hi, 

I had an issue where when an SVG is scaled in % rather than a value, the TopNavigation title is truncated. I fixed it by changing the scaling of the SVG to be set in values rather than %. Is there a way that would allows the TopNavigation Logo SVGs to be scaled in % without truncating the title?</div>

**Comment by taheramr** [comment] 2023-02-28 08:39
Hello, thanks for reaching out.

This looks like a valid bug and I was able to reproduce it, we are currently looking at different solutions to this and we'll keep you updated.

**Comment by taheramr** [comment] 2023-03-05 21:58
.

**Comment by taheramr** [comment] 2023-04-24 11:38
Sorry for the late replies on this bug, this [PR](https://github.com/cloudscape-design/components/pull/826) should fix the issue with the top navigation and full width/height svg logos.

Will followup when this is merged.

**Comment by taheramr** [comment] 2023-05-08 13:24
Hello again,

We are updating our components docs to guide developers to use fixed width and height for SVGs so they get rendered correctly without making the title text truncated in this [PR](https://github.com/cloudscape-design/components/pull/1069).

So the path forward for this would be editing your SVGs width and height or letting the [`viewBox`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) decide on the dimensions of the SVG.

I'm closing this as no further action is needed!
Amr

**Closed by taheramr** 2023-05-08 13:24 UTC
Labels: bug
