### ISSUE TITLE
playground example for Alert not dismissible

### ISSUE THREAD

**Issue by liamvdv** [cloudscape-design/components#558] opened 2022-12-05 19:03 UTC
### Description

The default code example for the Alert Component implements the hide functionality on dismiss, but doesn't show X for dismissing it. Fix by adding dismissible to the example. 
https://cloudscape.design/components/alert/?tabId=playground 

Suggestion:
```
import * as React from "react";
import Alert from "@cloudscape-design/components/alert";

export default () => {
  const [visible, setVisible] = React.useState(true);
  return (
    <Alert
      onDismiss={() => setVisible(false)}
      visible={visible}
      dismissable // <- ADDED 
      dismissAriaLabel="Close alert"
      header="Known issues/limitations"
    >
      Review the documentation to learn about potential
      compatibility issues with specific database
      versions.
    </Alert>
  );
}
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by timogasda** [comment] 2023-01-06 14:21
Hello!

Thank you for bringing this up. This is actually working as intended. This particular Alert example is not supposed to be dismissible, so it doesn't need the `dismissable` property. If anything, you could argue that the `dismissAriaLabel` property is unnecessary :) We'll go ahead and update those examples accordingly.

**Comment by just-boris** [comment] 2023-01-30 13:12
Planned fix has been deployed

**Closed by just-boris** 2023-01-30 13:12 UTC
Labels: documentation
