### ISSUE TITLE
[Bug]: Dependency issue for 3.0.515 Missing Export useRuntimeVisualRefresh

### ISSUE THREAD

**Issue by cnmoise** [cloudscape-design/components#1934] opened 2024-02-03 01:02 UTC
### Package version

3.0.515

### React version

18.2.0

### Description

I have tried installing the latest version of toolkit and global-styles but having the same issue

Here are all my packages:
```
    "@cloudscape-design/component-toolkit": "^1.0.0-beta.32",
    "@cloudscape-design/components": "^3.0.515",
    "@cloudscape-design/global-styles": "^1.0.22",
```

The error reads:

```
ERROR in ../node_modules/@cloudscape-design/components/internal/hooks/use-visual-mode/index.js 7:4-27
export 'useRuntimeVisualRefresh' (imported as 'useRuntimeVisualRefresh') was not found in '@cloudscape-design/component-toolkit/internal' (possible exports: COMPONENT_METADATA_KEY, Metrics, createSingletonHandler, createSingletonState, initAwsUiVersions, isDevelopment, isMotionDisabled, useComponentMetadata, useComponentMetrics, useCurrentMode, useDensityMode, useReducedMotion, useResizeObserver, useStableCallback, warnOnce)
```

### Reproduction

upgrade components to v3.0.515

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by cnmoise** [comment] 2024-02-03 01:07
Here is my full list of dependencies:

```
{
  "name": "admin-web-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/pubsub": "^5.1.13",
    "@aws-amplify/ui-react": "^5.3.1",
    "@cloudscape-design/component-toolkit": "^1.0.0-beta.32",
    "@cloudscape-design/components": "^3.0.515",
    "@cloudscape-design/global-styles": "^1.0.22",
    "@tanstack/react-query": "^4.14.6",
    "@tanstack/react-query-devtools": "^4.14.8",
    "@testing-library/jest-dom": "^5.14.1",
    "@types/node": "^18.11.9",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@types/uuid": "^9.0.4",
    "amazon-cognito-identity-js": "^5.2.12",
    "aws-amplify": "^5.3.11",
    "axios": "^1.6.0",
    "date-fns": "^2.30.0",
    "i18next": "^22.4.15",
    "i18next-http-backend": "^2.2.0",
    "jotai": "^1.9.2",
    "jsdoc": "^4.0.2",
    "lodash.isequal": "^4.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^12.2.0",
    "react-router-dom": "^6.4.2",
    "react-scripts": "5.0.1",
    "react-toastify": "^9.1.1",
    "typescript": "^4.4.2",
    "uuid": "^9.0.1",
    "web-vitals": "^2.1.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "lint": "eslint .",
    "test": "react-scripts test",
    "jest": "jest --verbose=true",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "@casualbot/jest-sonar-reporter": "^2.2.7",
    "@storybook/babel-plugin-require-context-hook": "^1.0.1",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^29.5.1",
    "@types/lodash.isequal": "^4.5.8",
    "@typescript-eslint/eslint-plugin": "^5.58.0",
    "@typescript-eslint/parser": "^5.58.0",
    "core-js": "^3.30.1",
    "eslint": "^8.38.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-import-resolver-typescript": "^3.5.5",
    "eslint-plugin-header": "^3.1.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsdoc": "^46.9.0",
    "eslint-plugin-json": "^3.1.0",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-yaml": "^0.5.0",
    "jest": "^29.5.0",
    "jest-environment-jsdom": "^29.5.0",
    "jest-junit": "^16.0.0"
  }
}
```

**Comment by just-boris** [comment] 2024-02-03 12:32
Duplicate of this: https://github.com/cloudscape-design/components/issues/1595

To avoid such issues in the future, do not edit the versions manually, use `npm upgrade`

**Closed by just-boris** 2024-02-03 12:32 UTC
Labels: bug

**Comment by cnmoise** [comment] 2024-02-05 19:10
Thanks Boris! Doing `yarn upgrade` with the new versions in the package resolved the error
