### ISSUE TITLE
[Feature Request]: Autosuggest

### ISSUE THREAD

**Issue by brianfoody** [cloudscape-design/components#103] opened 2022-08-02 08:18 UTC
### Description

I'd like to be able to enforce that AutoSuggest components require one of the suggested items rather than customers being able to enter a plaintext field through the enteredTextLabel.

I find it much better to use than a select component for quickly iterating though form inputs but being able to enter plaintext inhibits the usage.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

**Comment by timogasda** [comment] 2022-08-02 13:10
This looks like a duplicate of https://github.com/cloudscape-design/components/issues/104, so I'm closing this one.

**Closed by timogasda** 2022-08-02 13:10 UTC
Labels: enhancement
