### ISSUE TITLE
[Bug]: Table inline edit 'tick' icon does not save changes when clicked

### ISSUE THREAD

**Issue by jarrahffe** [cloudscape-design/components#3149] opened 2024-12-18 13:20 UTC
### Browser

Chrome

### Package version

3.0.848

### React version

18.3.1

### Description

for the `Table` component, during inline edit, clicking the 'tick' icon does nothing and i can't find any way to control what this tick icon does when clicked - please advise :)
when i say "does nothing", i mean literally nothing happens. the value doesn't "save". the only time something does happen is if i have not edited the value at all, then when i click the icon i see a green tick with a circle around it, see below image
an `onSubmit` field in `editConfig` for the tick icon would be nice, unless im using this completely wrong. i have also tried this with a validation function and there's no difference
<img width="276" alt="image" src="https://github.com/user-attachments/assets/e3d1d920-7d08-4355-bd7a-15d6a75d076a" />
<img width="201" alt="image" src="https://github.com/user-attachments/assets/1d95d101-6962-44bd-8dac-6fc470c54168" />

### Source code

          {
            id: "description",
            header: "Description",
            cell: (e) => e.description,
            sortingField: "description",
            editConfig: {
              editingCell: (emulationItem, { currentValue, setValue }) => {
                return (
                  <Input
                    autoFocus={true}
                    value={currentValue ?? emulationItem.description}
                    onChange={event => setValue(event.detail.value)}
                    placeholder="Enter Emulation Description"
                  />
                );
              },
            },
          },

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by gethinwebster** [comment] 2024-12-20 13:56
You can find a live example of inline editing working here: https://cloudscape.design/examples/react/table-editable.html

And the underlying source code for reference: https://github.com/cloudscape-design/demos/blob/main/src/pages/table-editable/index.jsx

**Comment by Al-Dani** [comment] 2024-12-23 16:48
hi @jarrahffe ,
You need to implement the saving operation on your end. We provide the information about the requested change in `submitEdit` property's payload.  As Gethin mentioned, you can find [an example](https://github.com/cloudscape-design/demos/blob/main/src/pages/table-editable/root.tsx#L110) in our demos.

That said, it's not a bug.
I'll close the issue, but feel free to create a discussion if you have any more questions

**Closed by Al-Dani** 2024-12-23 16:48 UTC
Labels: bug

**Comment by jarrahffe** [comment] 2024-12-24 01:17
@Al-Dani thank you heaps, just saw the submit edit field, thats my bad. Cheers
